midexamayaay/urls.py
from django.contrib import admin
from django.urls import path, include
from votes import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('votes/', include('votes.urls')),
]

votes/urls.py
from django.urls import path
from . import views
app_name = 'votes'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('candidate_create/', views.candidate_create, name = 'candidate_create'),
    path('position_create/', views.position_create, name = 'position_create'),
    path('<int:candidate_id>/', views.candidate_detail, name='candidate_detail'),
    path('<int:candidate_id>/candidate_update', views.candidate_update, name='candidate_update'),
    path('<int:candidate_id>/vote', views.vote, name='vote'),

]

votes/models.py
from django.db import models

# Create your models here.

class Position(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.name

class Candidate(models.Model):
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    birthdate = models.DateTimeField("Birthdate")
    platform = models.TextField()

    def __str__(self):
        return self.lastname + ", " + self.firstname

class Vote(models.Model):
    candidate = models.ForeignKey(Candidate, on_delete=models.CASCADE)
    vote_datetime = models.DateTimeField("Date Voted", auto_now_add=True)

    def __str__(self):
        return self.vote_datetime

votes/forms.py
from django.forms import ModelForm
from .models import Candidate, Position, Vote

class CandidateModelForm(ModelForm):
    class Meta:
        model = Candidate
        exclude = ['id']

class PositionModelForm(ModelForm):
    class Meta:
        model = Position
        exclude = ['id']

class VoteModelForm(ModelForm):
    class Meta:
        model = Vote
        exclude = ['id']

votes/views.py
from django.shortcuts import render, redirect
from .models import Position, Vote, Candidate
from .forms import PositionModelForm, VoteModelForm, CandidateModelForm

# Create your views here.

def index(request):
    context = {}
    context['candidates'] = Candidate.objects.all().order_by('position')
    return render(request, 'index.html', context)

def candidate_create(request):
    context = {}
    context['form'] = CandidateModelForm()

    if request.method == 'POST':
        form = CandidateModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            return render(request, 'candidate_create.html', context)
    else:
        return render(request, 'candidate_create.html', context)

def candidate_detail(request, candidate_id):
    context = {}
    context['candidate'] = Candidate.objects.get(id=candidate_id)
    return render(request, 'candidate_detail.html', context)

def candidate_update(request, candidate_id):
    context = {}
    post = Candidate.objects.get(id=candidate_id)

    if request.method == 'POST':
        form = CandidateModelForm(request.POST, instance=post)

        if form.is_valid():
            form.save()
            return redirect('/votes/' + str(candidate_id))
        else:
            context['form']  = form
            return render(request, 'candidate_update.html', context)

    else:
        context['form'] = CandidateModelForm(instance=post)
    return render(request, 'candidate_update.html', context)

def position_create(request):
    context = {}
    context['form'] = PositionModelForm()

    if request.method == 'POST':
        form = PositionModelForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect('/votes/')
        else:
            return render(request, 'position_create.html', context)
    else:
        return render(request, 'position_create.html', context)

def vote(request, candidate_id):
    print("here" + str(candidate_id))
    x = Vote(candidate = Candidate.objects.get(id=candidate_id))
    x.save()
    return redirect('/votes/')

votes/templates/base.html
{% load static %}

<html>
    <head>
        <title>
            {% block head %}

            {% endblock head %}
        </title>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/css/foundation.min.css" integrity="sha256-itWEYdFWzZPBG78bJOOiQIn06QCgN/F0wMDcC4nOhxY=" crossorigin="anonymous" />

        {% block styles %}
        {% endblock styles %}
    </head>

    <body>
        <nav class="navbar navbar-light bg-light static-top">
            <a class="navbar-brand" href='{% url 'votes:index' %}'>Posts</a>
        </nav>

        <div class="container">
            {% block body %}
                123456
            {% endblock body %}
        </div>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"> </script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/foundation/6.3.1/js/foundation.min.js" integrity="sha256-Nd2xznOkrE9HkrAMi4xWy/hXkQraXioBg9iYsBrcFrs=" crossorigin="anonymous"></script>

        {% block scripts %}

        {% endblock %}
    </body>
</html>

votes/templates/candidate_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}


{% block head %}
    Add New Candidate
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:candidate_create'%}" method="POST">
        {% csrf_token %}

        {{ form|crispy }}

        <input type="submit" value="Add">
    </form>
{% endblock body %}

votes/templates/candidate_detail.html
{% extends 'base.html' %}

{% block head %}
{% endblock head %}

{% block body %}

        <div class="row mt-5 mb-3">
                <h1> {{ candidate.lastname }}, {{ candidate.firstname }} <a href='{% url 'votes:candidate_update' candidate.id %}'> <span class="badge badge-secondary">Edit</span> </a> </h1>
        </div>

        <div class="row">
                <small> Position: {{ candidate.position }}</small>
        </div>
        <div class="row">
                <small> Birthdate: {{ candidate.birthdate }}</small>
                 <small> {{ candidate.vote_set.count}} votes </small>
        </div>
        <div class="row">
                <p class="text-justify mt-5 mb-5"> {{ candidate.platform }} <p>
        </div>

        <a href='{% url 'votes:vote' candidate.id %}'> <span class="btn btn-outline-primary ml-3">VOTE</span> </a>



{% endblock body %}

votes/templates/candidate_update.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    The Update Page
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:candidate_update' form.instance.id %}" method="POST">
        {% csrf_token %}

        <div class="row mt-5 mb-3">
                <h1> Edit "{{ form.lastname.value }}, {{ form.firstname.value }}" </h1>
        </div>

             {{ form|crispy }}
        <input type="submit" value="Update">
    </form>
{% endblock body %}

votes/templates/index.html
{% extends "base.html" %}

{% block head %}
    Candidates List
{% endblock head %}

{% block body %}
    <div class="row mt-5 mb-5">
        <h2 class="ml-3"> All Candidates
            <a href='{% url 'votes:position_create' %}'> <span class="btn btn-outline-primary ml-3">Add New Position</span> </a>
            <a href='{% url 'votes:candidate_create' %}'> <span class="btn btn-outline-primary ml-3">Add New Candidate</span> </a>
        </h2>
    </div>
    <div class="list-group">
        {% for candidate in candidates %}
            <a href="{% url 'votes:candidate_detail' candidate.id %}" class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1">{{ candidate.lastname }}, {{ andidate.firstname }}</h5>
                    <small> {{ candidate.vote_set.count }} votes </small>
                </div>

                <p class="mb-1"> {{ candidate.position }} </p>
            </a>

        {% endfor %}
    </div>
{% endblock body %}

votes/templates/position_create.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block head %}
    Add New Position
{% endblock head %}

{% block body %}
    <form action="{% url 'votes:position_create'%}" method="POST">
        {% csrf_token %}

        {{ form|crispy }}

        <input type="submit" value="Add">
    </form>
{% endblock body %}